# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase'
pod 'Firebase/Messaging'

target 'MyRideDNA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyRideDNA

  target 'MyRideDNA-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyRideDNATests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'MyRideDNA-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyRideDNA-tvOS

  #target 'MyRideDNA-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
  #end

#end
